version: "3.0"
services:
  tests:
    build:
      context: ./
      dockerfile: phpunit.dockerfile
    container_name: template-engine-test
    volumes:
      - "./src:/var/www/src"
      - "./tests:/var/www/tests"
    working_dir: /var/www
    command: ["./vendor/bin/phpunit", "--testdox", "tests"]